env:
  browser: false
  node: true
  es6: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:prettier/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - "@typescript-eslint"
ignorePatterns:
  - "**/api_bo/src/types.ts"
  - "**/api_m/src/types.ts"
