version: "3.2"

services:
  api_bo:
    image: denoland/deno:debian-1.23.4
    volumes:
      - type: bind
        source: ./packages/api_bo
        target: /usr/src
    ports:
      - 6005:3000
    command: bash -c "cd /usr/src && deno task start"
    depends_on:
      - mongo_db
    environment:
      - MONGO_URL=mongodb://mongo_db:27017/academy_db

  api_m:
    image: denoland/deno:debian-1.23.4
    volumes:
      - type: bind
        source: ./packages/api_m
        target: /usr/src
    ports:
      - 6010:4000
    command: bash -c "cd /usr/src && deno task start"
    depends_on:
      - mongo_db
    environment:
      - MONGO_URL=mongodb://mongo_db:27017/academy_db

  mongo_db:
    image: mongo:5
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ./data:/data/db
    command: mongod --logpath=/dev/null
    ports:
      - 27017:27017