version: "3.2"

services:
  api_bo:
    image: denoland/deno:debian-1.23.4
    volumes:
      - type: bind
        source: ./packages/api_bo
        target: /usr/src
    ports:
      - 6005:3000
    command: bash -c "cd /usr/src && deno task start"
    depends_on:
      - mongo_db
    environment:
      - MONGO_URL=mongodb://mongo_db:27017/academy_db

  api_m:
    image: denoland/deno:debian-1.23.4
    volumes:
      - type: bind
        source: ./packages/api_m
        target: /usr/src
    ports:
      - 6010:4000
    command: bash -c "cd /usr/src && deno task start"
    depends_on:
      - mongo_db
    environment:
      - MONGO_URL=mongodb://mongo_db:27017/academy_db

  front_bo:
    image: node:16
    environment:
      REACT_APP_API_URL: http://localhost:6005
      PORT: 3000
    volumes:
      - type: bind
        source: ./packages/front_bo
        target: /usr/src
    depends_on:
      - api_bo
    ports:
      - 3000:3000
    command: bash -c "cd /usr/src && npm run dev"

  front_m:
    image: node:16
    environment:
      REACT_APP_API_URL: http://localhost:6010
      PORT: 3000
    volumes:
      - type: bind
        source: ./packages/front_m
        target: /usr/src
    depends_on:
      - api_m
    ports:
      - 8000:3000
    command: bash -c "cd /usr/src && npm run dev"

  mongo_db:
    image: mongo:5
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ./data:/data/db
    command: mongod --logpath=/dev/null
    ports:
      - 27017:27017